spring:
  application.name: pill-buddy
  profiles.include: db

  jpa:
    properties.hibernate:
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      jdbc:
        batch_size: 100
    hibernate.ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  token:
    client-secret: ${JWT_SECRET_KEY}
    access-expiration-time: 300000 # 5분
    refresh-expiration-time: 86400000  # 24시간

oauth:
  oauth2-password: ${KAKAO_PASSWORD}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    caregiver-redirect-uri: ${KAKAO_CAREGIVER_REDIRECT_URI}
    caretaker-redirect-uri: ${KAKAO_CARETAKER_REDIRECT_URI}
    authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}

file:
  path: test-upload


openApi:
  dataType: json
  serviceKey: ${LOCAL_SERVICE_KEY}
  callbackUrl: http://apis.data.go.kr/1471000/DrbEasyDrugInfoService/getDrbEasyDrugList

sms:
  api-key: ${API_KEY}
  api-secret-key: ${API_SECRET_KEY}
  domain: https://api.coolsms.co.kr
  from-number: 01039536296
